// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Support API",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/application/jobpost/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permet à un recruteur de voir toutes les candidatures pour une offre d'emploi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Récupérer les candidatures d'une offre",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'offre d'emploi",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Liste des candidatures",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Accès refusé - recruteurs uniquement",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Offre d'emploi non trouvée",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/application/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permet à un candidat de voir toutes ses candidatures",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Récupérer mes candidatures",
                "responses": {
                    "200": {
                        "description": "Liste de mes candidatures",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Accès refusé - candidats uniquement",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/application/{id}": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permet à un candidat de postuler à une offre d'emploi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Créer une candidature",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'offre d'emploi",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Données de la candidature",
                        "name": "applicationData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/applicationDto.CreateApplicationDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Candidature créée avec succès",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Accès refusé - candidats uniquement",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/application/{id}/state": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permet à un recruteur de changer le statut d'une candidature (pending, matched, rejected, accepted)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "applications"
                ],
                "summary": "Mettre à jour le statut d'une candidature",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la candidature",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nouveau statut",
                        "name": "stateData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/applicationDto.UpdateApplicationStateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Statut mis à jour avec succès",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Accès refusé - recruteurs uniquement",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Candidature non trouvée",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Authentifie un utilisateur avec email et mot de passe",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Connexion utilisateur",
                "parameters": [
                    {
                        "description": "Données de connexion",
                        "name": "loginData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authDto.LoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token JWT et informations utilisateur",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Identifiants incorrects",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère les informations de l'utilisateur connecté",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Profil utilisateur actuel",
                "responses": {
                    "200": {
                        "description": "Informations utilisateur",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Token manquant ou invalide",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/signup/candidate": {
            "post": {
                "description": "Crée un nouveau compte candidat",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Inscription candidat",
                "parameters": [
                    {
                        "description": "Données d'inscription candidat",
                        "name": "candidateData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authDto.CandidateRegisterDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Compte créé avec succès",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Email déjà utilisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/signup/recruiter": {
            "post": {
                "description": "Crée un nouveau compte recruteur",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Inscription recruteur",
                "parameters": [
                    {
                        "description": "Données d'inscription recruteur",
                        "name": "recruiterData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/authDto.RecruterRegisterDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Compte créé avec succès",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "409": {
                        "description": "Email déjà utilisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/certification": {
            "get": {
                "description": "Récupère la liste de toutes les certifications disponibles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certifications"
                ],
                "summary": "Lister toutes les certifications",
                "responses": {
                    "200": {
                        "description": "Liste des certifications",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Crée une nouvelle certification",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certifications"
                ],
                "summary": "Créer une certification",
                "parameters": [
                    {
                        "description": "Données de la certification",
                        "name": "certificationData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/certificationDto.CreateCertificationDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Certification créée avec succès",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/company": {
            "get": {
                "description": "Récupère la liste de toutes les entreprises",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "companies"
                ],
                "summary": "Lister toutes les entreprises",
                "responses": {
                    "200": {
                        "description": "Liste des entreprises",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        },
        "/jobpost": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crée une nouvelle offre d'emploi (recruteurs uniquement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Créer une offre d'emploi",
                "parameters": [
                    {
                        "description": "Données de l'offre d'emploi",
                        "name": "jobData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/jobPostDto.CreateJobPostDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Offre d'emploi créée avec succès",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Accès refusé - recruteurs uniquement",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/jobpost/candidate": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère toutes les offres d'emploi disponibles (candidats uniquement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Lister les offres d'emploi pour candidats",
                "responses": {
                    "200": {
                        "description": "Liste des offres d'emploi",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Accès refusé - candidats uniquement",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/jobpost/company": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère les offres d'emploi de l'entreprise du recruteur connecté",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Lister les offres d'emploi de l'entreprise",
                "responses": {
                    "200": {
                        "description": "Liste des offres d'emploi de l'entreprise",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Accès refusé - recruteurs uniquement",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/jobpost/{id}": {
            "get": {
                "description": "Récupère les détails d'une offre d'emploi spécifique",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "jobs"
                ],
                "summary": "Récupérer une offre d'emploi par ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'offre d'emploi",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Relations à inclure (ex: skills,company)",
                        "name": "populate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Détails de l'offre d'emploi",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Offre d'emploi non trouvée",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/match": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Permet à un recruteur de créer un match entre un candidat et une offre d'emploi",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "matches"
                ],
                "summary": "Créer un match",
                "parameters": [
                    {
                        "description": "Données du match",
                        "name": "matchData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/matchDto.CreateMatchDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Match créé avec succès",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Accès refusé - recruteurs uniquement",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Candidat, offre d'emploi ou candidature non trouvé(e)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/skill": {
            "get": {
                "description": "Récupère la liste de toutes les compétences disponibles",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "skills"
                ],
                "summary": "Lister toutes les compétences",
                "responses": {
                    "200": {
                        "description": "Liste des compétences",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Crée une nouvelle compétence",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "skills"
                ],
                "summary": "Créer une compétence",
                "parameters": [
                    {
                        "description": "Données de la compétence",
                        "name": "skillData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/skillDto.CreateSkillDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Compétence créée avec succès",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère la liste de tous les utilisateurs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Lister tous les utilisateurs",
                "responses": {
                    "200": {
                        "description": "Liste des utilisateurs",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crée un nouveau utilisateur (admin uniquement)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Créer un utilisateur",
                "parameters": [
                    {
                        "description": "Données de l'utilisateur",
                        "name": "userData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userDto.CreateUserDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Utilisateur créé avec succès",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/me/skills": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Supprime des compétences du profil de l'utilisateur connecté",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Supprimer des compétences de l'utilisateur",
                "parameters": [
                    {
                        "description": "Compétences à supprimer",
                        "name": "skillsData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userDto.DeleteUserSkillsDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Compétences supprimées",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Ajoute des compétences au profil de l'utilisateur connecté",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Ajouter des compétences à l'utilisateur",
                "parameters": [
                    {
                        "description": "Compétences à ajouter",
                        "name": "skillsData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userDto.UpdateUserSkillsDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Compétences ajoutées",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Récupère les détails d'un utilisateur spécifique",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Récupérer un utilisateur par ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Détails de l'utilisateur",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Utilisateur non trouvé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour les informations d'un utilisateur",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Mettre à jour un utilisateur",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nouvelles données de l'utilisateur",
                        "name": "userData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userDto.UpdateUserDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Utilisateur mis à jour",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Erreur de validation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Utilisateur non trouvé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Supprime un utilisateur",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Supprimer un utilisateur",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Utilisateur supprimé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Non autorisé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Utilisateur non trouvé",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "applicationDto.CreateApplicationDTO": {
            "type": "object",
            "properties": {
                "candidate_id": {
                    "description": "from the url params \u0026 the middleware",
                    "type": "integer"
                },
                "cover_id": {
                    "type": "integer"
                },
                "jobpost_id": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "applicationDto.UpdateApplicationStateDTO": {
            "type": "object",
            "required": [
                "state"
            ],
            "properties": {
                "state": {
                    "description": "Ensure state is one of the allowed values",
                    "type": "string",
                    "enum": [
                        "pending",
                        "matched",
                        "rejected",
                        "accepted"
                    ]
                }
            }
        },
        "authDto.CandidateRegisterDTO": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "lastName",
                "password"
            ],
            "properties": {
                "availability": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "certifications": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "email": {
                    "type": "string"
                },
                "experienceYears": {
                    "type": "integer"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "preferedContract": {
                    "type": "string"
                },
                "preferedJob": {
                    "type": "string"
                },
                "resumeID": {
                    "type": "integer"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "authDto.LoginDto": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "authDto.RecruterRegisterDTO": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "lastName",
                "password"
            ],
            "properties": {
                "company": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "newCompany": {
                    "$ref": "#/definitions/companyDto.CreateCompanyDTO"
                },
                "password": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "certificationDto.CreateCertificationDTO": {
            "type": "object",
            "required": [
                "category",
                "name"
            ],
            "properties": {
                "category": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "companyDto.CreateCompanyDTO": {
            "type": "object",
            "required": [
                "companyName",
                "siret"
            ],
            "properties": {
                "companyName": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "siret": {
                    "type": "string"
                },
                "size": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            }
        },
        "jobPostDto.CreateJobPostDTO": {
            "type": "object",
            "required": [
                "contract_type",
                "description",
                "expiration_date",
                "location",
                "salary_range",
                "title"
            ],
            "properties": {
                "certifications": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "companyID": {
                    "type": "integer"
                },
                "contract_type": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "expiration_date": {
                    "type": "string"
                },
                "file_id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "salary_range": {
                    "type": "string"
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "matchDto.CreateMatchDTO": {
            "type": "object",
            "required": [
                "application_id",
                "candidate_id",
                "job_post_id"
            ],
            "properties": {
                "application_id": {
                    "type": "integer"
                },
                "candidate_id": {
                    "type": "integer"
                },
                "job_post_id": {
                    "type": "integer"
                }
            }
        },
        "skillDto.CreateSkillDTO": {
            "type": "object",
            "required": [
                "category",
                "name"
            ],
            "properties": {
                "category": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "userDto.CreateUserDTO": {
            "type": "object",
            "required": [
                "email",
                "firstName",
                "lastName",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "userDto.DeleteUserSkillsDTO": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/userDto.UpdateUserSkillsDTO"
                }
            }
        },
        "userDto.UpdateUserDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "userDto.UpdateUserSkillsDTO": {
            "type": "object",
            "properties": {
                "certifications": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "skills": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Skillly API",
	Description:      "API pour l'application Skillly - plateforme de matching entre candidats et recruteurs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
