FROM golang:1.24.4-alpine3.22
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod tidy && go mod verify
RUN go install github.com/air-verse/air@latest

RUN apk update && \
    apk add --no-cache \
    postgresql16-client

ENTRYPOINT [ "air" ]