services:
  back:
    container_name: Server
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
      - mongodb

  postgres:
    image: postgres:16.4
    container_name: skillly_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "3308:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: skillly_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27018:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro 
      - db_data:/mongo-data/db
volumes:
  db_data:
