services:
  back:
    container_name: Server
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4
    container_name: skillly_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "3308:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
