name: Pipeline CI/CD
on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - main

jobs:
  #  RUN GO TEST
  run-go-test:
    outputs:
      outcome: ${{job.status}}
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.4
        ports:
          - "3308:5432"
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: skilly_test
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      mongodb:
        image: mongo:latest
        ports:
          - "27018:27017"
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
          MONGO_INITDB_DATABASE: skilly_test
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23.1

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./back

      - name: Create empty .env file
        run: touch .env
        working-directory: ./back

      - name: Run tests
        env:
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 3308
          TEST_DB_USER: root
          TEST_DB_PASSWORD: root
          TEST_DB_NAME: skilly_test
          MONGO_URI: mongodb://localhost:27017/
        run: go test -v ./test
        working-directory: ./back

  # GET REPO NAME
  get-repo-name:
    runs-on: ubuntu-latest
    outputs:
      repo-name: ${{ github.repository }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repo name
        run: echo "Repo name is ${{ github.repository }}"

        id: get-repo-name
        # This is the output variable
        # We can access this variable in other jobs using `needs.get-repo-name.outputs.repo-name`
